name: kordon-vadim-344-lab5

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Installing the Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.6
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Download access.log
            run: wget https://gitlab.com/oyakivchik/logfile/-/raw/main/access.log
          - name: Execute logs_parser.py and parse logs
            run: python logs_parser.py access.log
          - name: Exe—Åute ip_email.py
            run: python ip_email.py
