name: Oleksander-Kopiievyi-344-Lab5
on:
  push:
    branches:
      - Oleksander-Kopiievyi-344
  pull_request:
    branches:
      - Oleksander-Kopiievyi-344
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Cloning the repository
            uses: actions/checkout@v2
          - name: Installing the Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.6
          - name: Change directory to "Lb5"
            run: cd Lab5/
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Download access.log
            run: wget https://gitlab.com/oyakivchik/logfile/-/raw/main/access.log
          - name: Exetute log_parser.py and parse logs
            run: python log_parser.py access.log
          - name: Exetute ip_email.py
            run: python ip_email.pys
